### ISSUE TITLE
algorithm basic

### ISSUE THREAD

**Issue by at15** [dyweb/web-intern#4]
for students who have never learned algorithm or data structure .... (还有就是学了跟没学一样的) 
- [ ] sort
- [ ] binary tree
- [ ] avl and ? .... can even remember names..... 
- [ ] graph
- [ ] bfs and dfs for folder

.... to be continued

**Comment by ComMouse** [comment]
:scream:

**Comment by at15** [comment]
@ComMouse we will have test on March 31 ..... so.... BTW: this will help you guys a lot when u need to find internship.

**Comment by ComMouse** [comment]
I have to prepare for this examination....?!....
:fallen_leaf:

**Comment by at15** [comment]
@ComMouse no
