### ISSUE TITLE
network basic

### ISSUE THREAD

**Issue by at15** [dyweb/web-intern#6]
- [ ] layer. ( don't know how to say english (啊喂，干嘛要这么装13写英语。。。我只是想过gre....)
- [ ] the age old question `What happens when you enter www.google.com in browser` 
- [ ] tcp hand shake?.... ( the course is still talking about cookie and session ... )

and some more .... feel like having final exam.

**Comment by ComMouse** [comment]
:sob:

**Comment by xsfour** [comment]
What happened...
![image](https://cloud.githubusercontent.com/assets/8097302/6881155/1023cb34-d58e-11e4-834b-0b4040d60285.png)

**Comment by at15** [comment]
@xsfour .... this is more complex than the original question....

**Comment by xsfour** [comment]
https://github.com/skyline75489/what-happens-when-zh_CN 
https://github.com/alex/what-happens-when/blob/master/README.rst
